[build]
builder = "nixpacks"
buildCommand = "npm install && cd apps/api && npm install && npx prisma generate && npx nest build && echo 'Build completed, checking files:' && ls -la && ls -la dist/"

[deploy]
startCommand = "cd apps/api && echo 'Starting app, current directory:' && pwd && echo 'Files available:' && ls -la dist/ && node dist/main.js"